
----------- Eliminar base de datos ------------

ALTER TABLE "plan" DROP CONSTRAINT FK_CLIE_PLAN;
ALTER TABLE detalle_plan DROP CONSTRAINT FK_DEST_DEPL;
ALTER TABLE detalle_plan DROP CONSTRAINT FK_PLAN_DEPL;
ALTER TABLE destino DROP CONSTRAINT FK_TIDE_DEST;
ALTER TABLE destino DROP CONSTRAINT FK_DECA_DEST;
ALTER TABLE cliente DROP CONSTRAINT FK_TIID_CLIE;
ALTER TABLE "plan" DROP CONSTRAINT FK_USUA_PLAN;

DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS destino CASCADE;
DROP TABLE IF EXISTS DESTINATION_CATEGORIES CASCADE;
DROP TABLE IF EXISTS detalle_plan CASCADE;
DROP TABLE IF EXISTS "plan" CASCADE;
DROP TABLE IF EXISTS tipo_destino CASCADE;
DROP TABLE IF EXISTS tipo_identificacion CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
